{
  "openapi": "3.0.2",
  "info": {
    "title": "MyGram API",
    "version": "1.0"
  },
  "servers": [{ "url": "http://127.0.0.1:5000/api" }],
  "paths": {
    "/login": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["login"],
        "description": "Login User",
        "summary": "Login User",
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "admin@mail.com",
                    "description": "Email User"
                  },
                  "password": {
                    "type": "string",
                    "example": "admin",
                    "description": "Password User"
                  }
                },
                "required": ["email", "password"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Succes Login",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "example": 200,
                      "type": "integer",
                      "format": "number"
                    },
                    "status": {
                      "example": "OK",
                      "type": "string",
                      "format": "string"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "id": "47568467394683",
                        "name": "Aditya",
                        "user_name": "adit",
                        "email": "adit@mail.com",
                        "created_at": "2022-11-01T10:23:47.362Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Validasi",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "example": 400
                    },
                    "status": {
                      "type": "string",
                      "example": "BAD_REQUEST"
                    },
                    "data": {
                      "type": "array",
                      "example": [
                        {
                          "field": "UserName",
                          "message": "This field is required"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "example": 500,
                      "type": "integer",
                      "format": "number"
                    },
                    "status": {
                      "example": "INTERNAL_SERVER_ERROR",
                      "type": "string",
                      "format": "string"
                    },
                    "data": {
                      "type": "object",
                      "example": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/register": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["register"],
        "description": "Register User",
        "summary": "Register User",
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string",
                    "example": "adit123",
                    "description": "username user"
                  },
                  "email": {
                    "type": "string",
                    "example": "admin@mail.com",
                    "description": "Email User"
                  },
                  "password": {
                    "type": "string",
                    "example": "admin",
                    "description": "Password User"
                  },
                  "age": {
                    "type": "integer",
                    "example": 10,
                    "description": "Umur User"
                  }
                },
                "required": ["email", "password"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Succes Login",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "example": 200,
                      "type": "integer",
                      "format": "number"
                    },
                    "status": {
                      "example": "OK",
                      "type": "string",
                      "format": "string"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "id": "47568467394683",
                        "name": "Aditya",
                        "user_name": "adit",
                        "email": "adit@mail.com",
                        "created_at": "2022-11-01T10:23:47.362Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Validasi",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "example": 400
                    },
                    "status": {
                      "type": "string",
                      "example": "BAD_REQUEST"
                    },
                    "data": {
                      "type": "array",
                      "example": [
                        {
                          "field": "UserName",
                          "message": "This field is required"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "example": 500,
                      "type": "integer",
                      "format": "number"
                    },
                    "status": {
                      "example": "INTERNAL_SERVER_ERROR",
                      "type": "string",
                      "format": "string"
                    },
                    "data": {
                      "type": "object",
                      "example": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/photo": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": ["photo"],
        "description": "Create Photo",
        "summary": "Create Photo",
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "example": "Holiday Photo",
                    "description": "Judul Photo"
                  },
                  "caption": {
                    "type": "string",
                    "example": "Mandalika",
                    "description": "Caption Photo"
                  },
                  "photo_url": {
                    "type": "string",
                    "example": "https://instagram.com",
                    "description": "Url Photo"
                  }
                },
                "required": ["title", "photo_url"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Succes Register",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "example": 200,
                      "type": "integer",
                      "format": "number"
                    },
                    "status": {
                      "example": "OK",
                      "type": "string",
                      "format": "string"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "id": "47568467394683",
                        "name": "Aditya",
                        "user_name": "adit",
                        "email": "adit@mail.com",
                        "created_at": "2022-11-01T10:23:47.362Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Validasi",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "example": 400
                    },
                    "status": {
                      "type": "string",
                      "example": "BAD_REQUEST"
                    },
                    "data": {
                      "type": "array",
                      "example": [
                        {
                          "field": "UserName",
                          "message": "This field is required"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "example": 500,
                      "type": "integer",
                      "format": "number"
                    },
                    "status": {
                      "example": "INTERNAL_SERVER_ERROR",
                      "type": "string",
                      "format": "string"
                    },
                    "data": {
                      "type": "object",
                      "example": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "in": "header",
        "bearerFormat": "JWT",
        "name": "Bearer-KEY",
        "description": "Authentication for API"
      }
    },
    "schemas": {
      "CreateOrUpdateCategory": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        }
      },
      "Category": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "500": {
        "description": "Internal server error",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "example": 500,
                  "type": "integer",
                  "format": "number"
                },
                "status": {
                  "example": "INTERNAL_SERVER_ERROR",
                  "type": "string",
                  "format": "string"
                },
                "data": {
                  "type": "object",
                  "example": null
                }
              }
            }
          }
        }
      }
    }
  }
}
